export const CASES = [
  {
    id: 1,
    case: 'Send Screen View',
    description: 'Example how sent screenView event',
    dataPath: '',
  },
  {
    id: 2,
    case: 'Send event for GA UA Structure',
    description: 'Example of event for GA UA Structure',
    dataPath: '',
  },
  {
    id: 3,
    case: 'Send event for GA4 Structure',
    description: 'Example of event for GA UA Structure',
    dataPath: '',
  },
  {
    id: 4,
    case: 'GA UA: Ecommerce: Просмотр списка товаров',
    description: 'Example of event for GA UA Structure',
    dataPath: '',
  },
  {
    id: 5,
    case: 'GA4: Ecommerce: Просмотр списка товаров',
    description: 'Example of event for GA4 Structure',
    dataPath: '',
  },
  {
    id: 6,
    case: 'GA UA: Ecommerce: Клик по товару из списка',
    description: 'Example of event for GA UA Structure',
    dataPath: '',
  },
  {
    id: 7,
    case: 'GA4: Ecommerce: Клик по товару из списка',
    description: 'Example of event for GA4 Structure',
    dataPath: '',
  },
  {
    id: 8,
    case: 'GA UA: Ecommerce: Просмотр товара',
    description: 'Example of event for GA UA Structure',
    dataPath: '',
  },
  {
    id: 9,
    case: 'GA4: Ecommerce: Просмотр товара',
    description: 'Example of event for GA4 Structure',
    dataPath: '',
  },
  {
    id: 10,
    case: 'GA UA: Ecommerce: Добавление товара в корзину',
    description: 'Example of event for GA UA Structure',
    dataPath: '',
  },
  {
    id: 11,
    case: 'GA4: Ecommerce: Добавление товара в корзину',
    description: 'Example of event for GA4 Structure',
    dataPath: '',
  },
  {
    id: 12,
    case: 'GA UA: Ecommerce: Удаление товара из корзины',
    description: 'Example of event for GA UA Structure',
    dataPath: '',
  },
  {
    id: 13,
    case: 'GA4: Ecommerce: Удаление товара из корзины',
    description: 'Example of event for GA4 Structure',
    dataPath: '',
  },
  {
    id: 14,
    case: 'GA UA: Ecommerce: Старт оформления покупки',
    description: 'Example of event for GA UA Structure',
    dataPath: '',
  },
  {
    id: 15,
    case: 'GA4: Ecommerce: Старт оформления покупки',
    description: 'Example of event for GA4 Structure',
    dataPath: '',
  },
  {
    id: 16,
    case: 'GA UA: Ecommerce: Покупка',
    description: 'Example of event for GA UA Structure',
    dataPath: '',
  },
  {
    id: 17,
    case: 'GA4: Ecommerce: Покупка',
    description: 'Example of event for GA4 Structure',
    dataPath: '',
  },
  {
    id: 18,
    case: 'GA UA: Ecommerce: Возврат',
    description: 'Example of event for GA UA Structure',
    dataPath: '',
  },
  {
    id: 19,
    case: 'GA4: Ecommerce: Возврат',
    description: 'Example of event for GA4 Structure',
    dataPath: '',
  },
  {
    id: 20,
    case: 'GA UA: Ecommerce: Просмотр промо',
    description: 'Example of event for GA UA Structure',
    dataPath: '',
  },
  {
    id: 21,
    case: 'GA4: Ecommerce: Просмотр промо',
    description: 'Example of event for GA4 Structure',
    dataPath: '',
  },
  {
    id: 22,
    case: 'GA UA: Ecommerce: Клик по промо',
    description: 'Example of event for GA UA Structure',
    dataPath: '',
  },
  {
    id: 23,
    case: 'GA4: Ecommerce: Клик по промо',
    description: 'Example of event for GA4 Structure',
    dataPath: '',
  },
  {
    id: 24,
    case: 'GA4: Ecommerce: Просмотр корзины',
    description: 'Example of event for GA4 Structure',
    dataPath: '',
  },
  {
    id: 25,
    case: 'GA4: Ecommerce: Добавление в список желаемого',
    description: 'Example of event for GA4 Structure',
    dataPath: '',
  },
  {
    id: 26,
    case: 'GA4: Ecommerce: Указание сведений о доставке',
    description: 'Example of event for GA4 Structure',
    dataPath: '',
  },
  {
    id: 27,
    case: 'GA4: Ecommerce: Указание сведений об оплате',
    description: 'Example of event for GA4 Structure',
    dataPath: '',
  },
];

export default CASES;
